// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents

//ClassDeliveryHelper.CreateDelivery();
//ClassDeliveryHelper.DeleteDelivery('a00QL00000GAvF7');

//ClassDeliveryHelper.ChangeCourse('a00QL00000GAva5', '.Net');